/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CinemaItemRequestBuilderRequestsMetadata, type CinemaItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Moive/cinema
 */
export interface CinemaRequestBuilder extends BaseRequestBuilder<CinemaRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.Moive.cinema.item collection
     * @param id Unique identifier of the item
     * @returns {CinemaItemRequestBuilder}
     */
     byId(id: string) : CinemaItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const CinemaRequestBuilderUriTemplate = "{+baseurl}/Moive/cinema";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const CinemaRequestBuilderNavigationMetadata: Record<Exclude<keyof CinemaRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: CinemaItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["Id"],
    },
};
/* tslint:enable */
/* eslint-enable */
