/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createMoiveDTOFromDiscriminatorValue, type MoiveDTO } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Moive/film/{Id}
 */
export interface FilmItemRequestBuilder extends BaseRequestBuilder<FilmItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MoiveDTO>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MoiveDTO | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FilmItemRequestBuilderUriTemplate = "{+baseurl}/Moive/film/{Id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const FilmItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: FilmItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createMoiveDTOFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
