/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createListMoiveResponseFromDiscriminatorValue, type ListMoiveResponse } from '../models/index.js';
// @ts-ignore
import { CinemaRequestBuilderNavigationMetadata, type CinemaRequestBuilder } from './cinema/index.js';
// @ts-ignore
import { FilmRequestBuilderNavigationMetadata, type FilmRequestBuilder } from './film/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Moive
 */
export interface MoiveRequestBuilder extends BaseRequestBuilder<MoiveRequestBuilder> {
    /**
     * The cinema property
     */
    get cinema(): CinemaRequestBuilder;
    /**
     * The film property
     */
    get film(): FilmRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ListMoiveResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ListMoiveResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MoiveRequestBuilderUriTemplate = "{+baseurl}/Moive";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const MoiveRequestBuilderNavigationMetadata: Record<Exclude<keyof MoiveRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    cinema: {
        navigationMetadata: CinemaRequestBuilderNavigationMetadata,
    },
    film: {
        navigationMetadata: FilmRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const MoiveRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MoiveRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, text/plain;q=0.9",
        adapterMethodName: "send",
        responseBodyFactory:  createListMoiveResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
