// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MovieDeal.DataSource.Cinemaworld.Movie.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MovieDeal.DataSource.Cinemaworld.Movie
{
    /// <summary>
    /// Builds and executes requests for operations under \cinemaworld\movie
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MovieRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MovieDeal.DataSource.cinemaworld.movie.item collection</summary>
        /// <param name="position">Unique identifier of the movie</param>
        /// <returns>A <see cref="global::MovieDeal.DataSource.Cinemaworld.Movie.Item.MovieItemRequestBuilder"/></returns>
        public global::MovieDeal.DataSource.Cinemaworld.Movie.Item.MovieItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::MovieDeal.DataSource.Cinemaworld.Movie.Item.MovieItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MovieDeal.DataSource.Cinemaworld.Movie.MovieRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MovieRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cinemaworld/movie", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MovieDeal.DataSource.Cinemaworld.Movie.MovieRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MovieRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/cinemaworld/movie", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
