// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using MovieDeal.DataSource.Filmworld.Movie;
using MovieDeal.DataSource.Filmworld.Movies;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MovieDeal.DataSource.Filmworld
{
    /// <summary>
    /// Builds and executes requests for operations under \filmworld
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FilmworldRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The movie property</summary>
        public global::MovieDeal.DataSource.Filmworld.Movie.MovieRequestBuilder Movie
        {
            get => new global::MovieDeal.DataSource.Filmworld.Movie.MovieRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The movies property</summary>
        public global::MovieDeal.DataSource.Filmworld.Movies.MoviesRequestBuilder Movies
        {
            get => new global::MovieDeal.DataSource.Filmworld.Movies.MoviesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MovieDeal.DataSource.Filmworld.FilmworldRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilmworldRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/filmworld", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MovieDeal.DataSource.Filmworld.FilmworldRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public FilmworldRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/filmworld", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
