/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { FilmItemRequestBuilderRequestsMetadata, type FilmItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Moive/film
 */
export interface FilmRequestBuilder extends BaseRequestBuilder<FilmRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.Moive.film.item collection
     * @param id Unique identifier of the item
     * @returns {FilmItemRequestBuilder}
     */
     byId(id: string) : FilmItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const FilmRequestBuilderUriTemplate = "{+baseurl}/Moive/film";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const FilmRequestBuilderNavigationMetadata: Record<Exclude<keyof FilmRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: FilmItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["Id"],
    },
};
/* tslint:enable */
/* eslint-enable */
